name: Continuous Integration
run-name: CI
on: [pull_request]

jobs:
  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: prettier
        run: yarn prettier

  build-project-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

  build-project-deployment:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build project for production
        run: yarn build
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: build/

  deploy:
    if: success() && contains( github.ref, 'master')
    runs-on: ubuntu-latest
    needs: [build-project-deployment]
    steps:
      - name: Down project artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-build

      - name: Deploy project to provider
        run: npm install -g --unsafe-perm=true netlify-cli && netlify deploy --dir=build --prod
